packages:
  - packages/*

catalog:
  '@types/node': ^22.0.0
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  eslint: 9.39.2
  next: ^16.1.0
  react: ^19.2.0
  react-dom: ^19.2.0
  typescript: ^5.2.0
